# Generated by Django 2.2.9 on 2020-02-02 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200201_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
